# Generated by Django 6.0.4 on 2026-04-14 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_projectimage_static_path_alter_projectimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitorpreference',
            name='layout',
            field=models.CharField(choices=[('carousel', 'Carousel'), ('grid', 'Grid'), ('list', 'List')], default='carousel', max_length=10),
        ),
    ]
