# Generated by Django 6.0.4 on 2026-04-15 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_site_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('static_path', models.CharField(max_length=200)),
                ('auto_caption', models.CharField(help_text='Auto-generated from filename. Never edited directly.', max_length=200)),
                ('caption', models.CharField(blank=True, help_text='Displayed caption. Edit this freely — seed command will not overwrite it.', max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
