# Generated by Django 6.0.4 on 2026-04-19 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='short_name',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
