# Generated by Django 6.0.4 on 2026-04-19 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_add_project_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='url_label',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
